# Generated by Django 4.1.3 on 2022-11-09 21:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenauth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='id',
            field=models.CharField(default=uuid.UUID('fdf88de5-05bb-4983-8964-ed3aacdab646'), editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tokenauth',
            name='id',
            field=models.CharField(default=uuid.UUID('89a3de15-cba3-431d-bd2e-f86e6983367a'), editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
