# Generated by Django 4.1.3 on 2022-11-09 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('token_auth', '0002_deviceinfo_created_at_tokenauth_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='id',
            field=models.CharField(default=uuid.UUID('853db20e-c408-4b2e-97c0-5331650fb163'), editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tokenauth',
            name='id',
            field=models.CharField(default=uuid.UUID('f90ea53f-bd46-4c44-a064-2fe8c49f8082'), editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tokenauth',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokenauth', to=settings.AUTH_USER_MODEL),
        ),
    ]
