# Generated by Django 4.1.3 on 2022-11-09 22:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0003_alter_deviceinfo_id_alter_tokenauth_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinfo',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tokenauth',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
