# Generated by Django 4.1.3 on 2022-11-08 22:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('6ddb369d-1d94-4e90-bfab-1bab1302019d'), editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
