# Generated by Django 4.1.3 on 2022-11-09 22:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('1fa29bc3-3310-45cf-993c-0889c8536e7f'), editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
